config/routes.rb
Zefa::Application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations", passwords: "users/passwords"}

  get 'usuario/:user_id/balancos/', to: 'balances#new', as: :new_balance
  post 'usuario/:user_id/balancos/', to: 'balances#create', as: :balances

  root to: 'users#index'
end

app/models/balance.rb
class Balance < ActiveRecord::Base
  belongs_to :user

  with_options presence: true do |p|
    p.validates :price
    p.validates :signal
    p.validates :color
  end

  validates :price,
            :numericality => true,
            :format => { :with => /\A\d{1,6}(\.\d{0,4})?\z/ }

  class << self
    def building params
      balance = BalanceValidate.new params[:price]
      signal, price, color = balance.separate
      create(price: price, signal: signal, user_id: params[:user_id], color: color)
    end
  end
end

app/models/balance_validate.rb
class BalanceValidate
  def initialize price
    @price = price.values[0]
  end

  def separate
    if @price.include?('-')
      spread << '#FF0000'
    elsif @price.include?('+')
      spread << '#008B00'
    else
      ["+", @price, '#008B00']
    end
  end

  private
  def spread
    @price.split(' ')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  # sanitize_for_mass_assignment :name, :email, :password, :password_confirmation, :remember_me

  has_many :balances
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  respond_to :html
end

app/controllers/balances_controller.rb
class BalancesController < ApplicationController
  def new
    user
    @balances = Balance.where(user_id: user.id)
    @balance = user.balances.build
    respond_with @balances
  end

  def create
    respond_with @balance = Balance.building(params[:balance]), location: new_balance_path(user.id)
  end

  private

  def user
    @user ||= User.find(params[:user_id])
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  private
  def resource_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  private
  def resource_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/balances/new.html.haml
%h3= @user.name

= form_for @balance, url: balances_path(params[:user_id]) do |f|
  = text_field :balance, :price, placeholder: 'Ex.: - 10.00', required: true
  = hidden_field_tag 'balance[user_id]', params[:user_id]
  %br
  = f.submit

%table
  %tbody
    - @balances.each do |balance|
      %tr
        %td= balance.signal
        %td{style: "color: #{balance.color}"}= balance.price
%br

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Zefa"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") Zefa
          .container.nav-collapse
            %ul.nav
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"

    .container-fluid
      .row-fluid
        .span9
          = bootstrap_flash
          = yield

      %footer
        %p= "&copy; Company #{Time.zone.now.strftime("%Y")}".html_safe
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"